name: Build-Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    if: ${{ github.repository_owner == 'TianMengLucky' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: build
        run: dotnet publish ./Installer/LiarsBarEnhanceInstaller.csproj

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: LiarsBarEnhanceInstaller
          path: ./Installer/bin/Release/net8.0/win-x64/publish/LiarsBarEnhanceInstaller.exe
          
      - name: build Cleaner
        run: dotnet publish ./ModCleaner/ModCleaner.csproj
        
      - name: upload Cleaner
        uses: actions/upload-artifact@v4
        with:
          name: ModCleaner
          path: ./ModCleaner/bin/Release/net8.0/win-x64/publish/ModCleaner.exe
        