name: Build-Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    if: ${{ github.repository_owner == 'TianMengLucky' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: build
        run: dotnet publish

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: LiarsBarEnhanceInstaller
          path: ./bin/Release/net8.0/publish/LiarsBarEnhanceInstaller.exe